version: 2

models:
  - name: indexes
    description: Postgres Indexes stats
    columns:
      - name: schemaname
        description: Index schema
      - name: tablename
        description: Table name
      - name: indexname
        description: Index name
      - name: tablespace
        description: Index tablespace
      - name: indexdef
        description: Index defenition
      - name: size
        description: Index size in Bytes

metrics:
  - name: count_indexes
    model: ref('indexes')
    label: Indexes by table
    calculation_method: count
    expression: indexname
    dimensions:
      - schemaname
      - tablename
